# 定义目标goal

bool                mode                    # true: 进电梯, false: 出电梯

geometry_msgs/Pose  takepose                # 当前楼层的乘梯点

geometry_msgs/Pose  waitpose                # 当前楼层的候梯点

geometry_msgs/Pose  door_point               # 当前楼层的备用乘梯点

geometry_msgs/Pose  target_goal              # 目标楼层目标点


---
# Define the result
bool result       # 成功１　失败０

---
# Define a feedback message
# constants state enum
uint8 NONE              = 0  # 初始化状态
uint8 SET_NEW_GOAL      = 1  # 收到新指令
uint8 NAV_WAIT          = 2  # 导航至候梯点
uint8 NAV_TAKE          = 3  # 导航至乘梯点
uint8 RETURN_WAIT_AREA  = 4  # 返回至候梯区域
uint8 IN_SUCCESS_TAKE   = 5  # 进梯成功-乘梯点
uint8 IN_SUCCESS_DOOR   = 6  # 进梯成功-门口
uint8 TAKE_ELEVATOR     = 7  # 乘坐电梯
uint8 NAV_OUT           = 8  # 出电梯
uint8 SUCCESS           = 9  # 成功
uint8 FAILURE_FULL      = 10 # 失败-满员
uint8 FAILURE           = 11 # 失败-异常
uint8 CANCLED           = 12 # 取消

uint8   feedback
string  feedback_text
