#request fields

#   "set"              设置乘梯信息(每次设置的信息必须包含楼层信息、梯控设备id、电梯控制区间、候梯点、乘梯点，会直接覆盖现有信息)
#   "modify_floor"     楼层信息修改(只修改楼层信息)
#   "get"              获取指定地图的乘梯信息
#   "delete"           清空指定地图的乘梯信息(所有内容清除)

#   每次的乘梯信息操作后都会返回被设定地图的乘梯信息

string                      cmd                 # 操作命令
string                      name                # 地图名称("null"代表设置当前正在使用的地图)
int32                       floor               # 楼层
Elevator[]                  elevator_info       # 电梯信息

---

#response fields

bool                        result              # 执行结果(请求是否成功执行)
int32                       floor               # 楼层
Elevator[]                  elevator_info       # 电梯信息
float32                     elevator_match_score  # 电梯匹配得分
